### ISSUE TITLE
New Block

### ISSUE THREAD

**Issue by enemali** [jfo8000/ScratchJr-Desktop#2]
In addition to the say block , i would love see a **Speak block**  this will entice the kids to hear their text read out (offline). This will encourage them learn spelling of words. 
i was thinking this might be possible during development using the _Web Speech API_.
it was implemented in scratch extension
http://sayamindu.github.io/scratch-extensions/text-to-speech/#intro
**code**
https://github.com/LLK/scratchx/tree/master

it's  nice to see this feature added or direct us on where to modify in the source code to achieve this.
Is this possible at all?

**Comment by jfo8000** [comment]
I agree.  Because it's a port, if it's not in the original I can't add new features.  But I will add this to a list and give it to my contact on the main scratch team for their next version.

May I suggest there is an ABC button at the top of the screen - this can aid in writing their own stories - especially if you have multiple scenes.  They could have a beginning scene, a middle scene and an end of the story scene.

**Comment by jfo8000** [comment]
I am going to tag this with 'suggestion' tag, and then collect and send suggestions.
