### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by kleberdexter** [jfo8000/ScratchJr-Desktop#3]
Do you intend to release a Linux version ?
Is to nardo to “compile” one version of your code to Linux ?
Thanks.

**Comment by jfo8000** [comment]
If you have a look at the releases, there is a .rpm and a .deb file that automatically compile.  

Fair warning: I have never ever tested it.  You're welcome to give it a go, but I make no guarantees! :)

https://github.com/jfo8000/ScratchJr-Desktop/releases

**Comment by jfo8000** [comment]
@kleberdexter  if you do try it let us know how it went - what platform you tried - and any setup instructions!

**Comment by ruebox** [comment]
@jfo8000 Just installed the linux version ScratchJr_1.3.2_amd64.deb
on 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

Works out of the box :-)

**Comment by jfo8000** [comment]
Amazing!  Thanks for reporting in! :)

**Comment by alkisg** [comment]
Hi guys, I just tested ScratchJr_1.3.2_amd64.deb under Ubuntu 18.04 64bit and it works great!

Two questions...

1. Why don't you put a link to it in https://jfo8000.github.io/ScratchJr-Desktop/ ? We have hundreds of schools here using Linux, some would really like to use it.
2. Is it possible to build a 32bit version? If not, is it just about the `debuild` effort (which I could probably do myself), or is there some dependency that is only available in 64bits?

Thank you!

**Comment by jfo8000** [comment]
1. I can certainly do that.  I had only put up releases I have actually tested.
2. Regarding 32 bit, it is an Electron app.  

You may still be able to eek out a 32 bit build out of it but not for long.  Electron is discontinuing support for 32 bit: https://electronjs.org/blog/linux-32bit-support

The builds are made with another package called electron-forge.  I notice that in package.json I do already have a line setup for 'npm run make32', which would be your starting clue.  Basically you want 'npm run package' and pass in the architecture.

All of this has to be done on a 32 bit machine.... which I'm not sure if my build maker Travis.ci supports - which is why I haven't built it out.

So the answer to number 2 is "Maybe?"   But the platform wont support it for long.   You're absolutely welcome to give it a shot and let us all know how it went!

JFo

**Comment by mkpc1** [comment]
Hi there, I tested the 64bit Linux version and it works great in my perconal laptop. I'm an IT teacher and i showed it  to my students in school lab and they were excited. Unfortunately we still use 32bit desktops there and there is no chance for an upgrade to 64bit computers for this year.  If a 32bit version becomes available, I'll also be able to use it in school with them. So let me know if there is a possibility. Thanks in advance.

**Comment by jfo8000** [comment]
I had a quick look last night... the version that this is running is Electron 6, which no longer supports 32 bit linux.  The reason for this is that the chrome platform it uses stopped being supported in 2016.   

It doesn't look like this is possible.  There is a windows 32 bit build available, but not sure that would help your situation.   :(

JFo

**Comment by alainbebe** [comment]
Hi,
With Debian 10 I have a problem. "libgconf-2-4" is installed but Scratch said "libgconf2-4" is not installed.
May be difference with "f-2" and "f2" ?

# apt install libgconf-2-4
....
libgconf-2-4 est déjà la version la plus récente (3.2.6-5).

dpkg -i ScratchJr_1.3.2_amd64.deb 
scratchjr dépend de libgconf2-4 ; cependant :
....
  Le paquet libgconf2-4 n'est pas installé.

**Comment by mebordone** [comment]
Can you fix the deb package? 
I've changed the dependencies of the deb package from libgconf2-4 to libgconf-2-4 and it works! If you can change it for all it would be great!

**Comment by mebordone** [comment]
Second problem
i've installed the deb version over linuxmint 20.2 (based on 20.04). When i run ScratchJr got this message. 
(ScratchJr:50777): Pango-ERROR **: 12:32:14.727: Harfbuzz version too old (1.4.2)

i'm tying to follow this instructions
https://unix.stackexchange.com/questions/589993/pango-error-harfbuzz-version-too-old

but may be is good put the problem here too for reporting.

**Comment by alkisg** [comment]
Since scratux stopped being maintained, we've switched to the official method for packaging scratch-desktop that is described there:
https://github.com/LLK/scratch-desktop/issues/117#issuecomment-964544549

Packages are available in .deb, .rpm, .snap, .appimage etc formats.
