### ISSUE TITLE
Opening .sjr files?

### ISSUE THREAD

**Issue by gajahduduk** [jfo8000/ScratchJr-Desktop#6]
Is it possible to open .sjr files (as exported from iPad version via Mail), and if so, how?  If not, is it possible to implement? 

Thanks.

**Comment by jfo8000** [comment]
Thanks for the question.  There is limited support for importing, and it is only from files created within Scratch JR for Desktop itself. 

You can save off sets of projects within Scratch JR desktop itself by copying it's database.  

> For classroom use, sometimes it is handy to pre-configure a set of projects. All of the projects all save into the same Documents/ScratchJR/scratchjr.sqllite file. To set up projects beforehand, you can make a backup copy of this file. 
> 
> Here's how.
>
> Make starter projects for your class - set up Scratch Jr with the projects you want everyone to use.
> Open up the ScratchJR folder inside of Documents
> Copy the scratchjr.sqllite file to scratchjr.sqllite.restore
> Re-open ScratchJR for desktop.
>
> After completing, there will be a menu option for restoring the projects. This will reset all the projects back to a clean copy of your projects. This is handy for a shared classroom setting where you don't wish to save the work between students. 

When I looked at the import / export screen I thought about implementing it.   The problem is that it would be difficult to support all the various versions of scratch jr running on different ipads/androids - if the file format changed it would be hard to keep up.  So this version really only understands the files it has generated itself. 

I will note this to the official scratch team as a feature you want to see in their more official releases.

**Comment by valeriu-leu** [comment]
I am building an exporter/importer here if anybody needed to export to mobile version and viceversa: https://gitlab.com/val.leu/scratchjr-importer-exporter/-/blob/main/README.md
